# Generated by Django 5.0.7 on 2024-07-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createrecord',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
