# Generated by Django 5.0.7 on 2024-08-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_alter_createrecord_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createrecord',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
